### ISSUE TITLE
build_vrt command assumes absolute paths

### ISSUE THREAD

**Issue by aaime** [noaa-ocs-hydrography/BlueTopo#17]
Calling build_vrt with a relative path appears to work, but produces VRTs that do not work (at least, do not work in QGIS)
E.g.:

```
build_vrt -d bluetopo_tiles
```

where ``bluetopo_tiles`` is a sub-directory of the current path works, starts up, builds the VRTs, but then the VRTs only show up while the overviews are used, while the visualization disappears zooming in enough that the actual source files are used.

This happens because the vrt itself ends up assuming relative paths:

```
      <SourceFilename relativeToVRT="0">bluetopo_tiles/BlueTopo/UTM14/BlueTopo_BH4JM56W_20221130.tiff</SourceFilename>
```

Passing an absolute path to the command produces VRTs that work no matter from where in the file system they are used. Maybe it should either force using absolute paths, or if you want to make it portable to other file systems, use paths relative to the VRT?

**Comment by GlenRice-NOAA** [comment]
Thanks for the thoughts!

I use these VRTs in QGIS (we are in 3.30 or later) without issue, so maybe there is a system or configuration issue as well?  If the VRT file itself is not moved I think relative pathing should work.  

We are currently doing a bit of rehashing of how the source data can be pulled.  We can look at adding a kwarg that allows for switching to absolute pathing as I think that should be relative simple.

**Comment by pgeleg** [comment]
I looked into this, albeit very briefly so some of this could be wrong, but heres my thoughts on two solutions

1. If a user passes in a relative path, we can just resolve it into an absolute path. This should be an easy fix, but as mentioned the paths referenced in the VRT file would be absolute. Sending VRTs and their corresponding files to others would still be a problem. But it should fix the issue mentioned.

2. In order to get relative paths in the VRT, by making sure that the VRT is in the same directory or in a parent directory of the files that it references, GDAL appears to convert any paths to relative by default. This is the easiest, but it comes with the caveat that we would need to modify the existing directory structure to (probably) a less than ideal one.

   If we don't want to change our directory structure, we can still get relative references but it looks like we need to change the working directory before calling `gdal.BuildVRT()` so that all paths can be passed in as relative paths. Particularly, I think we need to change the working directory so that its exactly where the VRT file is being created. After changing the working directory, we have to pass both the VRT output path and the GeoTIFF paths as relative. Meaning the VRT output path would be passed in as just the filename. Not doing these things seems to result in varying behaviors. So there appears to be some particularities and current GDAL functionality doesn't seem to exist to make it easier from my (very) brief look at it, but it's possible to make it work through existing functionality without hacking at the file ourselves. I don't love the idea of changing a users working directory inside the program. I also don't love the idea of hacking at the file ourselves. So I think I would prefer either changing our directory structure so GDAL resolves paths to relative on its own or seeing if GDAL provides another means of doing what we want, if we want relative paths.

Right now we're probably in the worst middle option which for the UTM VRTs, the subregion VRTs they reference are in a  subdirectory so their paths are made relative by GDAL by default, but the GeoTIFF files are referenced as absolute. Which is the most restrictive combination for the user.

**Comment by pgeleg** [comment]
- The file path references in the VRT file can now be either relative or absolute. There is a new argument in the `build_vrt` command named `relative_to_vrt`, which will default to true. In this default case, file paths inside the VRT will be relative. Setting to false will make file paths inside the VRT to be absolute. You can end up in a mixed state with both if you use both at different times for the creation of various VRTs. I would stick to one to get the benefits of that option. As mentioned in my testing there was some obscure behavior in implementing this, which seems vulnerable to being changed by GDAL in the future. The current behavior this is implemented on is mentioned here https://lists.osgeo.org/pipermail/gdal-dev/2009-October/022358.html which is dated 2009 so maybe its relatively safe.

- Entered in path arguments to the commands will be required to be absolute for now. This is just regarding the project root path and the geometry path arguments. We will probably accept both absolute and relative in the future. Just need to think a bit on the most user friendly implementation.

Will let @GlenRice-NOAA close if all looks good in the PR
